export const SUBJECTS = [
    { name: "Mathematics" },
    { name: "Science" },
    { name: "English" },
    { name: "History" },
    { name: "Geography" },
    { name: "Physics" },
    { name: "Chemistry" },
    { name: "Biology" },
    { name: "Computer Science" },
    { name: "Art" },
    { name: "Music" },
    { name: "Physical Education" },
    { name: "Social Studies" },
    { name: "Economics" },
    { name: "Psychology" },
    { name: "Environmental Science" },
    { name: "Political Science" },
    { name: "Philosophy" },
    { name: "Business Studies" },
    { name: "Health Education" },
    { name: "Foreign Languages" }, // e.g., Spanish, French, German, etc.
    { name: "Drama/Theater" },
    { name: "Design and Technology" },
];

export const GENERIC_DATE_FORMAT = "MMMM dd, yyyy";

export const MODULES = {
    STUDENTS: "students",
    TEACHERS: "teachers",
    PARENTS: "parents",
    GRADES: "grades",
    CLASSES: "classes",
    LESSONS: "lessons",
    EXAMS: "exams",
    ASSIGNMENTS: "assignments",
    RESULTS: "results",
    ATTENDANCE: "attendance",
    EVENTS: "events",
    ANNOUNCEMENTS: "announcements",
};

const englishWords = [
    "apple",
    "banana",
    "cherry",
    "dragon",
    "elephant",
    "forest",
    "giraffe",
    "honey",
    "island",
    "jungle",
    "koala",
    "lemon",
    "mountain",
    "nectar",
    "ocean",
    "panda",
    "quartz",
    "river",
    "sunrise",
    "tiger",
    "umbrella",
    "violet",
    "whale",
    "xenon",
    "yacht",
    "zephyr",
    "amber",
    "breeze",
    "canyon",
    "dolphin",
    "ember",
    "flamingo",
    "glacier",
    "harbor",
    "iguana",
    "jade",
    "kite",
    "lagoon",
    "meadow",
    "nightfall",
    "opal",
    "pearl",
    "quokka",
    "reef",
    "sapphire",
    "topaz",
    "unicorn",
    "valley",
    "willow",
    "xerox",
    "yellow",
    "zenith",
    "azure",
    "blossom",
    "cascade",
    "daisy",
    "fern",
    "galaxy",
    "horizon",
    "iris",
    "jasper",
    "kite",
    "lotus",
    "mango",
    "nebula",
    "onyx",
    "phoenix",
    "quill",
    "rainbow",
    "sierra",
    "thunder",
    "utopia",
    "voyage",
    "wander",
    "xylophone",
    "yonder",
    "zephyrine",
    "mirage",
    "ember",
    "tempest",
    "crystal",
    "mist",
    "pebble",
    "shadow",
    "echo",
    "whirlpool",
    "zephyr",
    "mirage",
    "solstice",
    "twilight",
    "blizzard",
    "flurry",
    "ripple",
    "cascade",
    "vortex",
    "gale",
    "horizon",
];

const spanishWords = [
    "manzana",
    "banana",
    "cereza",
    "dragon",
    "elefante",
    "bosque",
    "jirafa",
    "miel",
    "isla",
    "selva",
    "koala",
    "limon",
    "montana",
    "nectar",
    "oceano",
    "panda",
    "cuarzo",
    "rio",
    "amanecer",
    "tigre",
    "paraguas",
    "violeta",
    "ballena",
    "xenon",
    "yate",
    "cefiro",
    "ambar",
    "brisa",
    "canon",
    "delfin",
    "ascua",
    "flamenco",
    "glaciar",
    "puerto",
    "iguana",
    "jade",
    "cometa",
    "laguna",
    "pradera",
    "anochecer",
    "opalo",
    "perla",
    "quimera",
    "arrecife",
    "zafiro",
    "topacio",
    "unicornio",
    "valle",
    "sauce",
    "xerografia",
    "amarillo",
    "cenit",
    "azul",
    "flor",
    "cascada",
    "margarita",
    "helecho",
    "galaxia",
    "horizonte",
    "iris",
    "jaspe",
    "papalote",
    "loto",
    "mango",
    "nebula",
    "onix",
    "fenix",
    "pluma",
    "arcoiris",
    "sierra",
    "trueno",
    "utopia",
    "viaje",
    "deambular",
    "xilofono",
    "alla",
    "zephyrino",
    "espejismo",
    "ascua",
    "temporal",
    "cristal",
    "niebla",
    "guijarro",
    "sombra",
    "eco",
    "remolino",
    "zephyr",
    "espejismo",
    "solsticio",
    "crepusculo",
    "ventisca",
    "remolino",
    "ola",
    "cascada",
    "vortice",
    "vendaval",
    "horizonte",
];

const frenchWords = [
    "pomme",
    "banane",
    "cerise",
    "dragon",
    "elephant",
    "foret",
    "girafe",
    "miel",
    "ile",
    "jungle",
    "koala",
    "citron",
    "montagne",
    "nectar",
    "ocean",
    "panda",
    "quartz",
    "riviere",
    "leverdusoleil",
    "tigre",
    "parapluie",
    "violet",
    "baleine",
    "xenon",
    "yacht",
    "zephyr",
    "ambre",
    "brise",
    "canyon",
    "dauphin",
    "braise",
    "flamant",
    "glacier",
    "port",
    "iguane",
    "jade",
    "cerfvolant",
    "lagon",
    "prairie",
    "crepuscule",
    "opale",
    "perle",
    "chimere",
    "recif",
    "saphir",
    "topaze",
    "licorne",
    "vallee",
    "saule",
    "xerox",
    "jaune",
    "zenith",
    "azur",
    "fleur",
    "cascade",
    "marguerite",
    "fougere",
    "galaxie",
    "horizon",
    "iris",
    "jaspe",
    "cerfvolant",
    "lotus",
    "mangue",
    "nebuleuse",
    "onyx",
    "phenix",
    "plume",
    "arcenciel",
    "sierra",
    "tonnerre",
    "utopie",
    "voyage",
    "errer",
    "xylophone",
    "labas",
    "zephyre",
    "mirage",
    "braise",
    "tempete",
    "cristal",
    "brouillard",
    "caillou",
    "ombre",
    "echo",
    "tourbillon",
    "zephyr",
    "mirage",
    "solstice",
    "crepuscule",
    "blizzard",
    "rafale",
    "ondulation",
    "cascade",
    "vortex",
    "bourrasque",
    "horizon",
];

const germanWords = [
    "apfel",
    "banane",
    "kirsche",
    "drache",
    "elefant",
    "wald",
    "giraffe",
    "honig",
    "insel",
    "dschungel",
    "koala",
    "zitrone",
    "berg",
    "nektar",
    "ozean",
    "panda",
    "quarz",
    "fluss",
    "sonnenaufgang",
    "tiger",
    "schirm",
    "violett",
    "wal",
    "xenon",
    "yacht",
    "zephyr",
    "bernstein",
    "brise",
    "schlucht",
    "delfin",
    "glut",
    "flamingo",
    "gletscher",
    "hafen",
    "leguan",
    "jade",
    "drache",
    "lagune",
    "wiese",
    "nacht",
    "opal",
    "perle",
    "chimare",
    "riff",
    "saphir",
    "topas",
    "einhorn",
    "tal",
    "weide",
    "xerox",
    "gelb",
    "zenit",
    "azur",
    "blume",
    "wasserfall",
    "margerite",
    "farn",
    "galaxie",
    "horizont",
    "iris",
    "jaspis",
    "drachen",
    "lotus",
    "mango",
    "nebel",
    "onyx",
    "phonix",
    "feder",
    "regenbogen",
    "gebirge",
    "donner",
    "utopie",
    "reise",
    "wandern",
    "xylophon",
    "dorthin",
    "zephyrine",
    "fata",
    "glut",
    "sturm",
    "kristall",
    "nebel",
    "kiesel",
    "schatten",
    "echo",
    "wirbel",
    "zephyr",
    "fata",
    "sonnenwende",
    "dammerung",
    "schneesturm",
    "bo",
    "welle",
    "wasserfall",
    "wirbel",
    "windstoss",
    "horizont",
];

const italianWords = [
    "mela",
    "banana",
    "ciliegia",
    "drago",
    "elefante",
    "foresta",
    "giraffa",
    "miele",
    "isola",
    "giungla",
    "koala",
    "limone",
    "montagna",
    "nettare",
    "oceano",
    "panda",
    "quarzo",
    "fiume",
    "alba",
    "tigre",
    "ombrello",
    "viola",
    "balena",
    "xenon",
    "yacht",
    "zefiro",
    "ambra",
    "brezza",
    "canyon",
    "delfino",
    "brace",
    "fenicottero",
    "ghiacciaio",
    "porto",
    "iguana",
    "giada",
    "aquilone",
    "laguna",
    "prato",
    "notte",
    "opale",
    "perla",
    "chimera",
    "scogliera",
    "zaffiro",
    "topazio",
    "unicorno",
    "valle",
    "salice",
    "xerox",
    "giallo",
    "zenit",
    "azzurro",
    "fiore",
    "cascata",
    "margherita",
    "felce",
    "galassia",
    "orizzonte",
    "iris",
    "diaspro",
    "aquilone",
    "loto",
    "mango",
    "nebula",
    "onice",
    "fenice",
    "piuma",
    "arcobaleno",
    "sierra",
    "tuono",
];

export const PWD_WORDS = [
    ...englishWords,
    ...spanishWords,
    ...frenchWords,
    ...germanWords,
    ...italianWords,
];
